# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20160103_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='viewer.Question'),
        ),
    ]
